spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/commentservicedb
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8083
