spring:
  datasource:
    url: jdbc:postgresql://place-db:5432/place-service
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 1100MB
      max-request-size: 1100MB
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9093
    template:
      default-topic: kafka-topic
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

server:
  port: 8081
  address: 0.0.0.0
