spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-group
    template:
      default-topic: kafka-topic

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8085
